# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('tax_name', models.CharField(max_length=30)),
                ('pre_tax_amount', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_app.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('first_name', 'last_name', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='expenseitem',
            unique_together=set([('date', 'category', 'description', 'tax_name', 'pre_tax_amount', 'tax_amount', 'total_amount', 'employee')]),
        ),
    ]
